###
# Start the container:
#   podman kube play podman-kube-play.yaml
#
# Stop it:
#   podman kube down podman-kube-play.yaml
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.podman.annotations.infra.name: infra-swf-devmode-pod
    bind-mount-options: ./swf:Z
  labels:
    app: swf-devmode-pod
  name: swf-devmode-pod
spec:
  hostNetwork: true
  hostname: mas-p1
  containers:
  - image: registry.redhat.io/openshift-serverless-1/logic-swf-devmode-rhel8:1.34.0
    name: swf-devmode
    securityContext:
      runAsNonRoot: true
    volumeMounts:
    - mountPath: /home/kogito/serverless-workflow-project/src/main/resources
      name: host-resources
  volumes:
  - hostPath:
      path: ./swf
      type: Directory
    name: host-resources
